name: pyemitenv
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py37hf985489_2
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py37h271585c_1
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - brotli=1.0.9=h0d85af4_6
  - brotli-bin=1.0.9=h0d85af4_6
  - ca-certificates=2021.10.8=h033912b_0
  - certifi=2021.10.8=py37hf985489_1
  - cffi=1.15.0=py37h446072c_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h811a1a6_3
  - debugpy=1.5.1=py37hd8d24ac_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.4.4=he49afe7_0
  - flit-core=3.6.0=pyhd8ed1ab_0
  - fonttools=4.29.1=py37h271585c_0
  - freetype=2.10.4=h4cff582_1
  - fribidi=1.0.10=hbcb3906_0
  - gettext=0.19.8.1=hd1a6beb_1008
  - giflib=5.2.1=hbcb3906_2
  - icu=64.2=h6de7cb9_1
  - importlib-metadata=4.10.1=py37hf985489_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=6.9.0=py37h4c52d7d_0
  - ipython=7.31.1=py37hf985489_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.1=py37hf985489_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9e=h0d85af4_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py37hf985489_7
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py37hf985489_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py37h737db71_1
  - lcms2=2.12=h577c468_0
  - lerc=3.0=he49afe7_0
  - libblas=3.9.0=13_osx64_openblas
  - libbrotlicommon=1.0.9=h0d85af4_6
  - libbrotlidec=1.0.9=h0d85af4_6
  - libbrotlienc=1.0.9=h0d85af4_6
  - libcblas=3.9.0=13_osx64_openblas
  - libcxx=12.0.1=habf9029_1
  - libdeflate=1.8=h0d85af4_0
  - libffi=3.4.2=h0d85af4_5
  - libgfortran=5.0.0=9_3_0_h6c81a4c_23
  - libgfortran5=9.3.0=h6c81a4c_23
  - libglib=2.70.2=hf1fb8c0_2
  - libiconv=1.16=haf1e3a3_0
  - libimagequant=2.17.0=h9bde063_1
  - liblapack=3.9.0=13_osx64_openblas
  - libopenblas=0.3.18=openmp_h3351f45_0
  - libpng=1.6.37=h7cec526_2
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.3.0=hd146c10_2
  - libwebp=1.2.2=h28dabe5_0
  - libwebp-base=1.2.2=h0d85af4_1
  - libxcb=1.13=h0d85af4_1004
  - libzlib=1.2.11=h9173be1_1013
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.3=he49afe7_1
  - markupsafe=2.0.1=py37h271585c_1
  - matplotlib=3.5.1=py37hf985489_0
  - matplotlib-base=3.5.1=py37h3147e9e_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py37h271585c_1005
  - munkres=1.1.4=pyh9f0ad1d_0
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.1=py37hf985489_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.3=he49afe7_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - notebook=6.4.8=pyha770c72_0
  - numpy=1.21.5=py37h3c8089f_0
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=3.0.0=h0d85af4_2
  - packaging=21.3=pyhd8ed1ab_0
  - pandoc=2.17.1.1=h694c41f_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=he49afe7_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py37h942db99_0
  - pip=22.0.3=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - prompt_toolkit=3.0.26=hd8ed1ab_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyqt=5.9.2=py37h2a560b1_4
  - pyrsistent=0.18.1=py37h271585c_0
  - python=3.7.12=hf3644f1_100_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pyzmq=22.3.0=py37h8f778e5_1
  - qt=5.9.7=h8cf7e54_3
  - qtconsole=5.2.2=pyhd8ed1ab_1
  - qtconsole-base=5.2.2=pyhd8ed1ab_1
  - qtpy=2.0.1=pyhd8ed1ab_0
  - readline=8.1=h05e3726_0
  - scipy=1.7.3=py37h4e3cf02_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.8.1=py37hf985489_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h23a322b_0
  - terminado=0.13.1=py37hf985489_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h5dbffcc_1
  - tornado=6.1=py37h271585c_2
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - unicodedata2=14.0.0=py37h271585c_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py37hf985489_1
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h9173be1_1013
  - zstd=1.5.2=h582d3a0_0
prefix: /Users/smiskov/opt/anaconda3/envs/pyemitenv
