name: emit-env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.10.0=py37_0
  - anyio=3.5.0=py37hf985489_0
  - appnope=0.1.2=py37hf985489_1
  - argon2-cffi=20.1.0=py37h271585c_2
  - astor=0.8.1=py37_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bayesian-optimization=1.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.3.1=pyhd8ed1ab_0
  - brotlipy=0.7.0=py37h271585c_1003
  - c-ares=1.16.1=haf1e3a3_0
  - ca-certificates=2021.10.8=h033912b_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2021.10.8=py37hf985489_1
  - cffi=1.14.6=py37hda351d9_0
  - cryptography=36.0.1=py37h5e77fcc_0
  - cycler=0.10.0=py_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h4cff582_1
  - google-pasta=0.2.0=py_0
  - hdf5=1.10.6=hdbbcd12_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=258
  - ipykernel=5.5.5=py37h85f7c60_0
  - ipython=7.26.0=py37h4c52d7d_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37hf985489_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=0.17.0=py_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37hf985489_0
  - jupyter_server=1.13.4=pyhd8ed1ab_0
  - jupyterlab=3.2.8=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.10.3=pyhd8ed1ab_0
  - keras-applications=1.0.8=py_1
  - kiwisolver=1.3.1=py37h23ab428_0
  - libcxx=10.0.0=1
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=h7cec526_2
  - libprotobuf=3.13.0.1=hab81aa3_0
  - libsodium=1.0.18=hbcb3906_1
  - llvm-openmp=10.0.0=h28b9765_0
  - markdown=3.3.2=py37_0
  - markupsafe=2.0.1=py37h271585c_0
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py37hddda452_1
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py37h271585c_1004
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.2.0=py37hc64f4ea_0
  - mkl_random=1.1.1=py37h959d312_0
  - nbclassic=0.3.5=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.1.0=py37hf985489_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.0=pyha770c72_0
  - numpy=1.19.2=py37h456fd55_0
  - numpy-base=1.19.2=py37hcfb5961_0
  - openssl=1.1.1l=h0d85af4_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.1.3=py37hb1e8313_0
  - pandoc=2.14.1=h0d85af4_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=22.0.3=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - protobuf=3.13.0.1=py37hb1e8313_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h271585c_2
  - pysocks=1.7.1=py37hf985489_4
  - python=3.7.11=h88f2d9e_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytz=2020.1=py_0
  - pyzmq=20.0.0=py37h23ab428_1
  - readline=8.1=h9ed2024_0
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-learn=0.23.2=py37h959d312_0
  - scipy=1.5.2=py37h912ce22_0
  - send2trash=1.7.1=pyhd8ed1ab_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - six=1.15.0=py_0
  - sniffio=1.2.0=py37hf985489_2
  - sqlite=3.36.0=hce871da_0
  - termcolor=1.1.0=py37_1
  - terminado=0.10.1=py37hf985489_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py37h271585c_1
  - traitlets=5.0.5=py_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.3=pyhd8ed1ab_0
  - werkzeug=1.0.1=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h1de35cc_1
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - astunparse==1.6.3
    - build==0.7.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.10
    - cloudpickle==2.0.0
    - dataclasses==0.6
    - deprecated==1.2.13
    - dm-tree==0.1.6
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - gpflow==2.1.4
    - grpcio==1.32.0
    - h5py==2.10.0
    - keras==2.7.0
    - keras-preprocessing==1.1.2
    - libclang==12.0.0
    - multipledispatch==0.6.0
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - pep517==0.12.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - tabulate==0.8.9
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - tensorflow-probability==0.12.1
    - tomli==2.0.1
    - typing-extensions==3.7.4.3
prefix: /Users/smiskov/opt/anaconda3/envs/emit-env
