name: pyemitenv
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - expat=2.4.4
  - flit-core=3.6.0
  - fonttools=4.29.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - giflib=5.2.1
  - icu=64.2
  - importlib-metadata=4.10.1
  - importlib_resources=5.4.0
  - ipykernel=6.9.0
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.1.2
  - jupyter_console=6.4.0
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.3.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=12.0.1
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.70.2
  - libiconv=1.16
  - libimagequant=2.17.0
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclient=0.5.10
  - nbconvert=6.4.1
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.4
  - notebook=6.4.8
  - numpy=1.21.5
  - openjpeg=2.4.0
  - openssl=3.0.0
  - packaging=21.3
  - pandoc=2.17.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=22.0.3
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.26
  - prompt_toolkit=3.0.26
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyparsing=3.0.7
  - pyqt=5.9.2
  - pyrsistent=0.18.1
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.2.2
  - qtconsole-base=5.2.2
  - qtpy=2.0.1
  - readline=8.1
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=60.8.1
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.37.0
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.0.1
  - unicodedata2=14.0.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
prefix: /Users/smiskov/opt/anaconda3/envs/pyemitenv
