# conda env create -f environment-dev.yml
name: pyemittance-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - matplotlib-base
  - numpy
  - scipy
  - pyepics
  - pyyaml
# Developer
  - pytest
  - poppler
  - jupyterlab>=3
  - ipywidgets
  - pygments
  - mkdocs
  - mkdocstrings
  - mkdocs-material
  - mkdocs-jupyter
  - pip
  - pip:
    - mkdocstrings-python
    - pcaspy

